[alembic]
# Path to the migration scripts directory.  Changes to this
# parameter will require a new migration environment to be
# generated.
script_location = alembic

# Generic, backend-agnostic options for the environment.
# Defaults to "development" if not set.
# env = development

# The URL string used to connect to the database.
# This value can be overridden by the Alembic environment.
sqlalchemy.url = sqlite:///./alembic_temp.db

# Revision identifiers.
# current_revision = <revision_id>
# prev_revision = <revision_id>

# logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = INFO
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
formatter = generic
args = (sys.stderr,)

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
